package test

import (
	"fmt"
	"strconv"
	"time"

	. "github.com/go-yaaf/yaaf-common/entity"
	"golang.org/x/exp/rand"
)

// FlowRecord represents a single flow record from the CSV data
// generated by Suricata-based parser
type FlowRecord struct {
	FlowId        int64  `json:"flow_id" bigquery:"flow_id"`                 // Unique identifier for the flow
	StreamId      string `json:"stream_id" bigquery:"stream_id"`             // ID of the stream
	DeviceId      string `json:"device_id" bigquery:"device_id"`             // ID of the device
	StartTime     int64  `json:"start_time" bigquery:"start_time"`           // Start time of the flow in epoch seconds/microseconds
	EndTime       int64  `json:"end_time" bigquery:"end_time"`               // End time of the flow in epoch seconds/microseconds
	SrcIP         string `json:"src_ip" bigquery:"src_ip"`                   // Source IP address
	SrcPort       int    `json:"src_port" bigquery:"src_port"`               // Source port number
	DstIP         string `json:"dst_ip" bigquery:"dst_ip"`                   // Destination IP address
	DstPort       int    `json:"dst_port" bigquery:"dst_port"`               // Destination port number
	PcktToSrv     int    `json:"pckt_to_srv" bigquery:"pckt_to_srv"`         // Packets sent to the server
	PcktToClient  int    `json:"pckt_to_client" bigquery:"pckt_to_client"`   // Packets sent to the client
	BytesToSrv    int    `json:"bytes_to_srv" bigquery:"bytes_to_srv"`       // Bytes sent to the server
	BytesToClient int    `json:"bytes_to_client" bigquery:"bytes_to_client"` // Bytes sent to the client
	Proto         string `json:"protocol" bigquery:"protocol"`               // Protocol used (e.g., TCP, UDP)
	Alerted       bool   `json:"alerted" bigquery:"alerted"`                 // Whether the flow triggered an alert
	Pcap          string `json:"pcap" bigquery:"pcap"`                       // Associated PCAP file name
}

func (f *FlowRecord) TABLE() string { return "flow-data" }
func (f *FlowRecord) KEY() string   { return strconv.FormatInt(f.FlowId, 10) }
func (f *FlowRecord) ID() string    { return strconv.FormatInt(f.FlowId, 10) }
func (f *FlowRecord) NAME() string  { return strconv.FormatInt(f.FlowId, 10) }

func NewFlowRecordEntity() Entity {
	return &FlowRecord{}
}

// GenerateFlowRecords generates a specified number of FlowRecords and returns them as a slice
func generateFlowRecords(count int) []Entity {
	dstIPList := []string{
		"1.0.0.1", "103.235.46.96", "103.235.46.98", "103.235.47.188", "104.115.34.40",
		"104.17.111.223", "104.18.41.41", "104.18.8.54", "104.18.9.54", "104.21.17.143",
		// Add all other IPs from the provided list here...
		"216.58.215.164", "3.5.70.154",
	}
	protocols := []string{"TCP", "UDP", "ICMP"}
	streamIDs := []string{"etecnic-1", "etecnic-2", "etecnic-3"}

	rand.Seed(uint64(time.Now().UnixNano())) // Seed random number generator

	var records []Entity

	for i := 1; i <= count; i++ {
		startTime := time.Now().Add(time.Duration(-rand.Intn(1_000_000)) * time.Second).UnixMilli()
		endTime := startTime + int64(rand.Intn(300_000)) // Random duration between start and end

		record := &FlowRecord{
			FlowId:        int64(i),
			DeviceId:      fmt.Sprintf("device-%d", rand.Intn(100)),
			StartTime:     startTime / 1000,
			EndTime:       endTime / 1000,
			SrcIP:         fmt.Sprintf("10.%d.%d.%d", rand.Intn(256), rand.Intn(256), rand.Intn(256)), // Random IP in 10.0.0.0/8
			SrcPort:       rand.Intn(65535),
			DstIP:         dstIPList[rand.Intn(len(dstIPList))], // Random IP from the given list
			DstPort:       rand.Intn(65535),
			PcktToSrv:     rand.Intn(1000),
			PcktToClient:  rand.Intn(1000),
			BytesToSrv:    rand.Intn(1_000_000),
			BytesToClient: rand.Intn(1_000_000),
			Proto:         protocols[rand.Intn(len(protocols))],
			Pcap:          fmt.Sprintf("trace-%d.pcap", rand.Intn(100)),
			Alerted:       false, // Random true/false
			StreamId:      streamIDs[rand.Intn(len(streamIDs))],
		}
		records = append(records, record)
	}

	return records
}
